name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou a versão que você está usando

      - name: Instalar dependências do frontend
        working-directory: ./amazon-scraper-frontend
        run: npm install

      - name: Build do frontend
        working-directory: ./amazon-scraper-frontend
        run: npm run build
